config/routes.rb
Rails.application.routes.draw do
  resources :helloworldposts
  get "/login" , to:"session#login"
  post '/login',   to: 'session#create'
  get '/logout',  to: 'session#destroy'
  get "/", to:"session#index"
  root "session#index"

  
  get "/signup", to:"user#new"
  post "/signup", to:"user#create"
  
  get "/users/:id", to:"user#show"
  post "/users/:id", to:"user#uploadpic"

  get "/workspace", to:"workspace#index"

  get "/createchannel", to:"group#new"
  post "/createchannel", to:"group#create"

  get "/createworkspace", to:"workspace#create"
  post "/createworkspace", to:"workspace#create"
  get "/editworkspace", to:"workspace#new"
  
  get "/individualmessage", to:"individualmessage#index"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :workspace
  has_and_belongs_to_many :groups
end

app/models/groupmessage.rb
class Groupmessage < ApplicationRecord
  belongs_to :group
  has_and_belongs_to_many :groupthreadmessages
end

app/models/groupthreadmessage.rb
class Groupthreadmessage < ApplicationRecord
  belongs_to :groupmessage
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :image, presence: false
    validates :role, presence: false
    
    
  end
  

app/models/user_has_group.rb
class UserHasGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_has_workspace.rb
class UserHasWorkspace < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/workspace.rb
class Workspace < ApplicationRecord
    has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
    def new

    end
    def create
       g = Group.new(name:params[:name])
            render html:"#{params[:cbx_hidden]}"
       
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index
        
        if session[:user]
            
            @uhw = UserHasWorkspace.where(:workspace_id => session[:user]["currentworkspace"])
            @group = Group.where(:workspace_id => session[:user]["currentworkspace"])
        end
       
        render template:"home/index"
    end
    def login
        render template:"session/login"
    end
    def create
        user = User.find_by(email: params[:email].downcase)
        workspaces = Workspace.where(:owner => user.id)
        
        if user && user.authenticate(params[:password])
            #userhw = Userhasworkspace.find_by(user_id:user.id)
            #user.currentworkspace = userhw.workspace_id
            #user.save  
            
            #uhw = Userhasworkspace.where(:workspace_id=> user.currentworkspace)
            session[:workspaces] = workspaces
            session[:user_id] = user.id
            session[:user_name] = user.name
            session[:user]= user
            #session[:uhw] = uhw
            redirect_to "/"
        else
            render html:"Not success"
        end

    end
    def destroy
        session.delete(:user_id)
        session.delete(:user)
        redirect_to "/"
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    #before_action:logged_in_user, only:[:new, :show]
    def new

    end
    def create
        user = User.new(name:params[:name],email:params[:email].downcase,password:params[:password])
        
        
        if user.save
            workspace = Workspace.new(name:"CyberMissions Myanmar",owner:user.id)
            workspace.save
            user.currentworkspace = workspace.id
            user.save
            uhw = UserHasWorkspace.new(user_id:user.id,workspace_id:workspace.id)
            uhw.save
            workspaces = Workspace.where(:owner => user.id)
            session[:workspaces] = workspaces
            session[:user] = user
            session[:user_id] = user.id
            session[:user_name] = user.name
            redirect_to "/"
        else
            render html:"NOT"
        end
    end
    def show
        @user = User.find(params[:id])
    end
    def uploadpic

        name = params[:file]
        bn = File.absolute_path("public/upload/#{params[:file]}")
        #bn = File.extname(name)
        require 'fileutils'
        #FileUtils.move "#{bn}", 'public/upload'
         
        a = "C:/Users/CMM/Desktop/rails.jpg"
        FileUtils.cp a, "public/upload/"
        render html:"#{a}"
=begin
        require 'fileutils'
        FileUtils.move "Chrysanthemum.jpg", 'public/'
        user = User.find(params[:userid])
        a = params[:picture]
        user.image = a
        user.save
        render html:"#{user.image}"

        if user.save
            render html:"successful #{user.picture}"
        else
            render html:"Not"
        end
        #render html:"#{params[:picture]} #{params[:userid]}"
=end
    end
end

app/controllers/workspace_controller.rb
class WorkspaceController < ApplicationController
    def index
        @workspace =  Workspace.all
    end
    def create
        
    end

    def show
       
    end
    def new

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channelcontroller_helper.rb
module ChannelcontrollerHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/individualmessage_helper.rb
module IndividualmessageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/home/index.html.erb
<head>
    <style>
    input[type=text],input[type=password]{
        border:2px solid #CCC;
        border-bottom:2px solid springgreen;height:40px;border-radius:15px;font-family:time new roman;
    }
    input[type=submit]{
        border-radius:15px;font-family:time new roman;font-size:18px;
        color:black;
        font-weight:bold;
        background-color:springgreen;
        border:2px solid black;
        height:40px;
    }
    input[type=submit]:hover{
        color:white;
        background-color:springgreen;
    }
    body,html{
        width:100%;
        height:100%;
        background-image: linear-gradient(to right, springgreen , white);
    }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

</head>
<body>
<% if session[:user_id] %>
  <%= render template:"home/sidenav" %>
  <div style="background-color:grey;position:absolute;right:0;left:0;top:0;bottom:0;padding-left:351px;">
    <div style="width:100%;height:100%;background-color:grey;overflow:scroll">
    <% @uhw.each do |a| %>
      <%= a.user.name %>
    <% end %>
    </div>
    <input type="input" class="form-control" style="transform:translate(0,-100%);border:2px solid springgreen;height:40px;border-bottom:2px solid black;border-radius:15px;">
    <input type="submit" value"SEND" style="position:fixed;bottom:0;right:0;">
      
  </div>
<% else %>
<div class="row" style="width:100%;height:100%;">
    <div class="col-md-7">
        <img src="images/networking.png" style="width:80%;display:block;margin:0 auto;padding-top:5%;">
    </div>
    <div class="col-md-5" style="font-size:18px;padding:5% 0;font-family:Stencil Std, fantasy;">
    <div style="width:80%;display:block;margin:0 auto;padding-top:5%;padding:3% 3%;box-shadow:4px 4px 13px black;">
        <%= form_tag("/signup", method: "post") do %>
        <div class="form-group">
            <%=label_tag(:q,"Name")  %> 
            <input id="a" type="text" name="name" class="form-control">
        </div>  
                
        <div class="form-group">
          <%=label_tag(:q,"Email")  %> 
          <input type="text" name="email" class="form-control">
        </div>
        <div class="form-group">
          <%=label_tag(:q,"Password")  %> 
          <input type="password" name="password" class="form-control">
        </div>
        <div class="form-group">
          <%=label_tag(:q,"Confirm_password")  %> 
          <input type="password" name="confirm_password" class="form-control">
        </div>
        <div class="form-group">
          <input type="submit" value="SIGN UP" class="form-control" > 
          <%  end  %>
        </div>
    </div>
</div>

<% end %>
<script>
$(document).ready(function(){
  $("input").focus(function(){
    $(this).css({"border":"2px solid black","border-bottom":"2px solid limegreen"});
  });
  $("input").focusout(function(){
    $(this).css({"border":"2px solid #CCC","border-bottom":"2px solid springgreen"});
  });
});

</script>
</body>

app/views/home/sidenav.html.erb
<head>
    <style>
    html, body {
  height: 100%;
  margin: 0;
}

    #sidenav{
      background:url("images/night.jpg");
      background-position:center;
      background-repeat:no-repeat;
      background-attachment:fixed;
      background-size:cover;
    }
    ul#sidenavul1{
      list-style-type:none;
      margin:0;
      overflow:hidden;
      padding:0;
    }
    ul#sidenavul1 li{
      float:left;
      display:block;
      width:100%;
      margin:0;
    }
    ul#sidenavul1 li a{
      
      display:block;
      text-align:left;
      font-size:18px;
      color:springgreen;
      padding:10px;
      text-decoration:none;
      padding-left:10%;
      font-family:Courier New, monospace
    }
    ul#sidenavul1 li a:hover{
      background-color:springgreen;
      color:black;
    }

    ul#sidenavul2{
      list-style-type:none;
      margin:0;
      overflow:hidden;
      padding:0;
    }
    ul#sidenavul2 li{
      float:left;
      display:block;
      width:100%;
      margin:0;
    }
    ul#sidenavul2 li a{
      
      display:block;
      text-align:left;
      font-size:18px;
      color:springgreen;
      padding:10px;
      text-decoration:none;
      padding-left:10%;
      font-family:Courier New, monospace;
    }
    ul#sidenavul2 li a:hover{
      background-color:springgreen;
      color:black;
    }
    </style>
</head>
<body>
<div id="sidenav" style="z-index:3;width:350px;height:100%;position:fixed;top:0;left:0;font-family:Courier New, monospace">
    <p style="font-size:24px;padding:2% 0;color:white;font-family:Courier New, monospace">
    <div class="dropdown">
    <p class="dropdown-toggle" data-toggle="dropdown" style="font-size:18px;text-align:center;cursor:pointer;color:springgreen;">
    <% session[:workspaces].each do |a| %>
        <% if session[:user]["currentworkspace"] == a["id"] %>
          <%= a["name"] %>
        <% else %>
          
        <% end %>
    <% end %>
    <span class="caret"></span></p>
    <ul class="dropdown-menu" >
    <% session[:workspaces].each do |a| %>
      <% if a["id"] != session[:user]["currentworkspace"] %>
      <li style="cursor:pointer;"><a href="#" style="cursor:pointer;"><p style="font-size:18px;padding:2% 0;color:black;font-family:Courier New, monospace;">
        <%= a["name"] %></p></a></li>
      <% end %>
    <% end %>
    <li><a href="/createworkspace" style="cursor: pointer;"><p style="font-size:18px;padding:2% 0;color:black;font-family:Courier New, monospace;">CREATE WORKSPACE</p></a></li>
    <li><a href="/editworkspace" style="cursor: pointer;"><p style="font-size:18px;padding:2% 0;color:black;font-family:Courier New, monospace;">EDIT WORKSPACE</p></a></li>
    </ul>
  </div>
    <i class="fas fa-plus"></i></p>
    <div style="width:80%;height:300px;background-color:#2d2e30;border-radius:10px;display:block;margin:0 auto;margin-top:10%;">
      
    </div>
    <hr style="border:1px solid black;">
    <ul id="sidenavul1">
    <p style="font-size:24px;padding:2% 0;color:white;font-family:Courier New, monospace">Channels<i class="fas fa-plus"></i></p>
    <% @group.each do |a| %>
      <li><a href="#"><%= a.name %></a></li>
    <% end %>
    
    </ul>
    <hr style="border:1px solid black;">
    <ul id="sidenavul2">
    <p style="font-size:24px;padding:2% 0;color:white;font-family:Courier New, monospace">Direct Messages<i class="fas fa-plus"></i></p>
    <% @uhw.each do |a| %>
      <li><a href="#"><%= a.user.name %></a></li>
    <% end %>
    </ul>
    <hr style="border:1px solid black;">
    <div style="">
    <p style="font-size:24px;padding:2% 0;color:white;font-family:Courier New, monospace">Setting<i class="fas fa-plus"></i></p>
      <div style="padding:10px;">
      <p><a href="#" style="text-decoration:none;color:white;font-family:Courier New, monospace;font-size:18px;display:block;padding:2% 0;">Account Setting</a></p>
      <p><a href="#" style="text-decoration:none;color:white;font-family:Courier New, monospace;font-size:18px;display:block;padding:2% 0;">Text Format Setting</a></p>
      <p><a href="#" style="text-decoration:none;color:white;font-family:Courier New, monospace;font-size:18px;display:block;padding:2% 0;">User Management Setting</a></p>
      <p><a href="#" style="text-decoration:none;color:white;font-family:Courier New, monospace;font-size:18px;display:block;padding:2% 0;">Pravacy</a></p>
      <p><a href="/logout" style="text-decoration:none;color:white;font-family:Courier New, monospace;font-size:18px;display:block;padding:2% 0;">LOG OUT</a></p>
    
      </div>
    </div>
    
</div>
    <script>
    $(document).ready(function(){
      $("#sidenav").mouseenter(function(){
        $("#sidenav").css("overflow", "auto");
      });
      $("#sidenav").mouseleave(function(){
        $("#sidenav").css("overflow", "hidden");
      });
    });
    </script>
</body>

app/views/session/login.html.erb
<head>
    <style>
    input[type=text],input[type=password]{
        border:2px solid #CCC;
        border-bottom:2px solid springgreen;height:40px;border-radius:15px;font-family:time new roman;
        
       
    }
    input[type=submit]{
        border-radius:15px;font-family:time new roman;font-size:18px;
        color:black;
        font-weight:bold;
        background-color:springgreen;
        border:2px solid black;
        height:40px;
    }
    input[type=submit]:hover{
        color:white;
        background-color:springgreen;
    }
    </style>
</head>
<body>  
<div style="width:60%;display:block;margin:0 auto;padding:5%;">  
    <%= form_tag("/login", method: "post") do %>
          
                
    <div class="form-group">
      <%=label_tag(:q,"email")  %> 
      <input type="text" name="email" class="form-control">
    </div>
    <div class="form-group">
      <%=label_tag(:q,"password")  %> 
      <input type="password" name="password" class="form-control">
    </div>
    <div class="form-group">
      <%=submit_tag("LOG IN",class: "btn btn-primary form-control")   %> 
      <%  end  %>
      <p>New user? <%= link_to "Sign up now!", "/signup" %></p>
    </div>
</div>
</body>

app/views/session/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>
      
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>