config/routes.rb
Rails.application.routes.draw do
  resources :helloworldposts
  get "/login" , to:"session#login"
  post '/login',   to: 'session#create'
  get '/logout',  to: 'session#destroy'
  get "/", to:"session#index"
  root "session#index"

  
  get "/signup", to:"user#new"
  post "/signup", to:"user#create"
  
  get "/users/:id", to:"user#show"
  post "/users/:id", to:"user#uploadpic"

  get "/workspace", to:"workspace#index"

  get "/createchannel", to:"group#new"
  post "/createchannel", to:"group#create"

  get "/createworkspace", to:"workspace#create"
  post "/createworkspace", to:"workspace#create"
  get "/editworkspace", to:"workspace#new"
  
  get "/individualmessage", to:"individualmessage#index"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :workspace
  has_and_belongs_to_many :groups
end

app/models/groupmessage.rb
class Groupmessage < ApplicationRecord
  belongs_to :group
  has_and_belongs_to_many :groupthreadmessages
end

app/models/groupthreadmessage.rb
class Groupthreadmessage < ApplicationRecord
  belongs_to :groupmessage
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :image, presence: false
    validates :role, presence: false
    
    
  end
  

app/models/user_has_group.rb
class UserHasGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_has_workspace.rb
class UserHasWorkspace < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/workspace.rb
class Workspace < ApplicationRecord
    has_and_belongs_to_many :groups
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
    def new

    end
    def create
       g = Group.new(name:params[:name])
            render html:"#{params[:cbx_hidden]}"
       
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def index
        
        if session[:user]
            
            @uhw = UserHasWorkspace.where(:workspace_id => session[:user]["currentworkspace"])
            @group = Group.where(:workspace_id => session[:user]["currentworkspace"])
        end
       
        render template:"home/index"
    end
    def login
        render template:"session/login"
    end
    def create
        user = User.find_by(email: params[:email].downcase)
        workspaces = Workspace.where(:owner => user.id)
        
        if user && user.authenticate(params[:password])
            #userhw = Userhasworkspace.find_by(user_id:user.id)
            #user.currentworkspace = userhw.workspace_id
            #user.save  
            
            #uhw = Userhasworkspace.where(:workspace_id=> user.currentworkspace)
            session[:workspaces] = workspaces
            session[:user_id] = user.id
            session[:user_name] = user.name
            session[:user]= user
            #session[:uhw] = uhw
            redirect_to "/"
        else
            render html:"Not success"
        end

    end
    def destroy
        session.delete(:user_id)
        session.delete(:user)
        redirect_to "/"
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    #before_action:logged_in_user, only:[:new, :show]
    def new

    end
    def create
        user = User.new(name:params[:name],email:params[:email].downcase,password:params[:password])
        
        
        if user.save
            workspace = Workspace.new(name:"CyberMissions Myanmar",owner:user.id)
            workspace.save
            user.currentworkspace = workspace.id
            user.save
            uhw = UserHasWorkspace.new(user_id:user.id,workspace_id:workspace.id)
            uhw.save
            workspaces = Workspace.where(:owner => user.id)
            session[:workspaces] = workspaces
            session[:user] = user
            session[:user_id] = user.id
            session[:user_name] = user.name
            redirect_to "/"
        else
            render html:"NOT"
        end
    end
    def show
        @user = User.find(params[:id])
    end
    def uploadpic

        name = params[:file]
        bn = File.absolute_path("public/upload/#{params[:file]}")
        #bn = File.extname(name)
        require 'fileutils'
        #FileUtils.move "#{bn}", 'public/upload'
         
        a = "C:/Users/CMM/Desktop/rails.jpg"
        FileUtils.cp a, "public/upload/"
        render html:"#{a}"
=begin
        require 'fileutils'
        FileUtils.move "Chrysanthemum.jpg", 'public/'
        user = User.find(params[:userid])
        a = params[:picture]
        user.image = a
        user.save
        render html:"#{user.image}"

        if user.save
            render html:"successful #{user.picture}"
        else
            render html:"Not"
        end
        #render html:"#{params[:picture]} #{params[:userid]}"
=end
    end
end

app/controllers/workspace_controller.rb
class WorkspaceController < ApplicationController
    def index
        @workspace =  Workspace.all
    end
    def create
        
    end

    def show
       
    end
    def new

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channelcontroller_helper.rb
module ChannelcontrollerHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/helloworldposts/_form.html.erb
<%= form_with(model: helloworldpost, local: true) do |form| %>
  <% if helloworldpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(helloworldpost.errors.count, "error") %> prohibited this helloworldpost from being saved:</h2>

      <ul>
      <% helloworldpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/helloworldposts/edit.html.erb
<h1>Editing Helloworldpost</h1>

<%= render 'form', helloworldpost: @helloworldpost %>

<%= link_to 'Show', @helloworldpost %> |
<%= link_to 'Back', helloworldposts_path %>

app/views/helloworldposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Helloworldposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helloworldposts.each do |helloworldpost| %>
      <tr>
        <td><%= helloworldpost.title %></td>
        <td><%= helloworldpost.description %></td>
        <td><%= link_to 'Show', helloworldpost %></td>
        <td><%= link_to 'Edit', edit_helloworldpost_path(helloworldpost) %></td>
        <td><%= link_to 'Destroy', helloworldpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Helloworldpost', new_helloworldpost_path %>

app/views/helloworldposts/new.html.erb
<h1>New Helloworldpost</h1>

<%= render 'form', helloworldpost: @helloworldpost %>

<%= link_to 'Back', helloworldposts_path %>

app/views/helloworldposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @helloworldpost.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @helloworldpost.description %>
</p>

<%= link_to 'Edit', edit_helloworldpost_path(@helloworldpost) %> |
<%= link_to 'Back', helloworldposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Chatapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/mystyle.css" >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  
  <style>
      body{
      }
      
      a{
        
      }
  </style>
  </head>
  
  <body style="">
  
  <nav class="navbar navbar-inverse navbar-exp" style="background-color:springgreen;border:none;" >
  <div class="container-fluid">
    
    <div class="navbar-header">
      <a class="navbar-brand" href="#" style="font-size:18px;color:black;">CHAPAPP</a>
    </div>
    <ul class="nav navbar-nav">
      <!--
      <li class="active"><%= link_to "Home",   '#',{:style=>'font-size:18px;', :class => ""} %></li>
      
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><%= link_to "Home",   '#',{:style=>'font-size:18px;', :class => ""} %></li>
        <li><%= link_to "Help",   '#',{:style=>'font-size:18px;', :class => ""} %></li>
        <li><%= link_to "Log in", '#',{:style=>'font-size:18px;', :class => ""} %></li>
        </ul>
      </li>
      -->
      <li><%= link_to "Help",   '#',{:style=>'font-size:18px;color:black', :class => ""} %></li>
      
    </ul>
    <ul class="nav navbar-nav" style="float:right">
    <% if session[:user_id] %>
    <li style="float:right;"><%= link_to "Log out", '/logout',{:style=>'font-size:18px;float:right;color:white;', :class => ""} %></li>
    <% else %>
    <li><button type="button" style="margin-top:2px;" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">LOG IN</button></li>
    <% end %>
    </ul>
  </div>
</nav>
  <div> 
      <%=  yield  %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog" style="margin-top:10%">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="background-color:springgreen">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">LOGIN</h4>
        </div>
        <div class="modal-body">
          <% provide(:title, "Log in") %>
          
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <%= form_tag("/login", method: "post") do %>
          
                
                <div class="form-group">
                  <%=label_tag(:q,"email")  %> 
                  <input type="text" name="email" class="form-control">
                </div>
                <div class="form-group">
                  <%=label_tag(:q,"password")  %> 
                  <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group">
                  <%=submit_tag("LOG IN",class: "btn btn-primary form-control")   %> 
                  <%  end  %>
                  <p>New user? <%= link_to "Sign up now!", "/signup" %></p>
                </div>
            </div>
          </div>
          
        </div>
       
      </div>
      
    </div>
  </div>
  
</div>
  </body>
</html>